### ISSUE TITLE
Move to NationalGenomicsInfrastructure

### ISSUE THREAD

**Issue by johandahlberg** [NationalGenomicsInfrastructure/ngi_reports#24]
I'm wondering if this repo should not be moved to the NationalGenomicsInfrastructure, since the other pipeline components have their main repos there I think that would make sense.

**Comment by ewels** [comment]
Yup, you're probably right. [ngi_visualizations](https://github.com/SciLifeLab/ngi_visualizations) too really..

**Comment by johandahlberg** [comment]
Yeah. Do you want to fork them there?

**Comment by ewels** [comment]
Will it be confusing to leave it in the SciLifeLab organisation as well? Is it possible to move a repo entirely from one org to another?

**Comment by ewels** [comment]
([Yes](https://help.github.com/articles/transferring-a-repository/))

**Comment by ewels** [comment]
Done..

**Comment by ewels** [comment]
Also moved ngi_visualizations
