### ISSUE TITLE
Status DB connection doesn't work

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_reports#33]
Something in the statusdb code doesn't work when making IGN sample reports.

**Comment by senthil10** [comment]
@ewels : What is it :open_mouth:  Any particular message ?

**Comment by Galithil** [comment]
I think I got it, ngi_reports/stockholm/ign_sample_report.py line 25, this
should be name, not id

**Comment by ewels** [comment]
Yeah, it's not finding the project for some reason:
```
2015-03-13 14:37:42,141 - NGI Reports - INFO - Connecting to statusDB...
2015-03-13 14:37:42,476 - <class 'statusdb.db.connections.ProjectSummaryConnection'> - WARNING - no entry 'P1459' in <Database 'projects'>
2015-03-13 14:37:42,476 - NGI Reports - INFO - ...connected
2015-03-13 14:37:42,476 - NGI Reports - WARNING - Could not retrieve project details from statusdb for project P1459. Skipping...
```

I think @Galithil is looking into this as we speak. Any ideas?

**Comment by senthil10** [comment]
@Galithil : Yup, you are right. It should be the project name itself :)

@ewels : He got it already :joy:

**Comment by ewels** [comment]
Testing now :grinning:

![go team](http://cdn.meme.am/instances/500x/55074227.jpg)

**Comment by ewels** [comment]
```python
INFO:NGI Reports:Connecting to statusDB...
Traceback (most recent call last):
  File "/Users/philewels/Work/ngi_reports/scripts/ngi_reports", line 156, in <module>
    make_reports(**kwargs)
  File "/Users/philewels/Work/ngi_reports/scripts/ngi_reports", line 38, in make_reports
    report = report_mod.Report(config, LOG, working_dir, **kwargs)
  File "/Users/philewels/Work/ngi_reports/ngi_reports/stockholm/ign_sample_report.py", line 25, in __init__
    proj = pcon.get_entry(self.project['name'])
KeyError: 'name'
```

**Comment by senthil10** [comment]
according to [here](https://github.com/NationalGenomicsInfrastructure/ngi_reports/blob/master/ngi_reports/common/__init__.py#L59) should it be `ign_name` :eyes:

**Comment by ewels** [comment]
@senthil10: `ign_name` and `id` are synonymous, so that gives the same error as at first.

@Galithil thinks that it's because we have the ID in the form `P...` instead of `A.Test_...`

**Comment by senthil10** [comment]
@ewels : No, I mean for the `KeyError`, shouldn't it be ```proj = pcon.get_entry(self.project['ign_name'])```  instead of ```proj = pcon.get_entry(self.project['name'])``` and yes will get the same error like before  even after changing to `ign_name` as they (`ign_name` and `id`) are same (like you said) :smile:

**Comment by senthil10** [comment]
@ewels  and @Galithil : have made a [PR](https://github.com/SciLifeLab/statusdb/pull/7), so when it is merged you can use project id in `get_entry()` with one extra parameter. Say like

```
proj = pcon.get_entry(self.project['name'], use_id_view=True)
```

**Comment by ewels** [comment]
Awesome! Thanks :grinning:

Did you test `ngi_reports` with this change locally? Does it work?

**Comment by senthil10** [comment]
Well I dint check for `ngi_reports`, but I did check the function by calling with a project id instead of project name. So it returned what it supposed to (the project db dict for that project). So I would say it will work :+1: :sweat_smile:

**Comment by ewels** [comment]
Jättebra!
