### ISSUE TITLE
Error in pandocfilters install instructions

### ISSUE THREAD

**Issue by johandahlberg** [NationalGenomicsInfrastructure/ngi_reports#38]
The install instructions of pandocfilters state:

    cd data/pandoc_templates/pandocfilters/
    python setup.py install

However, there is no such file in the specified folder.

**Comment by ewels** [comment]
Really? I have it: https://github.com/jgm/pandocfilters

Are you sure you did `--recursive` and got the submodules when you cloned the repo?

**Comment by johandahlberg** [comment]
Sorry. Missed that part of the instructions.

**Comment by ewels** [comment]
No worries, you're not the first :) I should probably emphasise it in the docs. More bold text or something maybe.
