### ISSUE TITLE
Cant handle swedish characters 

### ISSUE THREAD

**Issue by parlundin** [NationalGenomicsInfrastructure/ngi_reports#41]
``` python
Traceback (most recent call last):
  File "/proj/a2014205/software/ngi_reports/scripts/ngi_reports", line 156, in <module>
    make_reports(**kwargs)
  File "/proj/a2014205/software/ngi_reports/scripts/ngi_reports", line 69, in make_reports
    print(output_md, file=fh)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 293: ordinal not in range(128)
```

**Comment by ewels** [comment]
For [sample](https://genomics-status.scilifelab.se/project/P1426) which has `Ö` in the user name.

Need to force string to be printed with correct encoding. Maybe [this](http://stackoverflow.com/questions/19273624/python-2-7-unicode-error-within-a-function-using-future-print-function-and)?
```python
print ("Döés thîß wørk? Åärghh!".encode('L9'))
```
Or UTF-8 or something.

**Comment by pekrau** [comment]
Use UTF-8!

**Comment by ewels** [comment]
@pekrau: Just copying and pasting from that SO answer :wink: Any idea why we need to go out of our way to specify UTF-8? I had in my head that `print()` handles this kind of stuff for you..

**Comment by pekrau** [comment]
This is a nightmare, I have never fully understood it. Maybe this helps: http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script
I have set this in my own machines, so I don't have to bother with it.

**Comment by remiolsen** [comment]
You mean something like 
```print (u"Döés thîß wørk? Åärghh!".encode('utf-8'))```

To use encode the object needs to be of type() `unicode`.. I don't think it'll work for `str`, if I'm not confused by how python does this :eyes:

**Comment by pekrau** [comment]
Rather, this is the advice I follow: http://gpiot.com/blog/python-set-character-encoding-utf-8/

I have been told that this is bad practice, for some reason. But I don't care.

**Comment by Galithil** [comment]
@ewels Python3 has native utf-8 encoding, i believe. unfortunately, we are still using 2, so legacy and things.

**Comment by pekrau** [comment]
OK, now I am getting angry at myself. This is what I have actually done:

```python
# install the apport exception handler if available
try:
    import apport_python_hook
except ImportError:
    pass
else:
    apport_python_hook.install()

# Per Kraulis 2014-01-21
import sys
sys.setdefaultencoding('utf-8')
```

**Comment by pekrau** [comment]
Yes, this is a Python 2 issue.

**Comment by ewels** [comment]
Nice, thanks @pekrau :+1: 

What's `apport_python_hook`?

**Comment by pekrau** [comment]
Don't know. It was there before I edited the file.

**Comment by mariogiov** [comment]
I'm a little surprised this has not broken the ngi_pipeline. Though sometimes I actually plan these things ahead and am later pleased with past Mario for making my life easier. Usually he just makes me deal with his problems.

**Comment by ewels** [comment]
Future me always [seems](http://waitbutwhy.com/2015/03/procrastination-matrix.html) like a nice guy..
![future me](http://28oa9i1t08037ue3m1l0i861.wpengine.netdna-cdn.com/wp-content/uploads/2015/03/FT1.png)

**Comment by aanil** [comment]
ngi_reports is ported to python3, so this should no longer be an issue. Another issue will be created if problems occur when running on python3.
