### ISSUE TITLE
Make pretty labels for Pass / Fail

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_reports#42]
Currently, the report has table values which are PASS, FAIL, PASSED and FAILED.
- [ ] Remove the 'ed' for consistency
- [ ] Sentence case
- [ ] Add subtle HTML class with green / red colouring.

PASSED -> `Pass`

**Comment by sofiahag** [comment]
Closing since nothing has been done for 8 years.

**Comment by ewels** [comment]
Doesn't mean that it was a bad idea 😉 😝

**Comment by sofiahag** [comment]
I know, sorry 😆 but I feel like it would be left here until the end of days. But you're right, I can make a Trello card, otherwise nothing will get done!

**Comment by sofiahag** [comment]
https://github.com/NationalGenomicsInfrastructure/ngi_reports/pull/152
