### ISSUE TITLE
Unable to create ign_sample_report with swedish number formatting 

### ISSUE THREAD

**Issue by Smeds** [NationalGenomicsInfrastructure/ngi_reports#68]
ngi_reports are unable to parse `genome_results.txt` file from qualimap, when the output has been generated using swedish number formatting, i.e with spaces and commas.

Example

> ```
> number of windows = 483
> 
> number of reads = 1 066 442 816
> number of mapped reads = 1 049 993 798 (98,46%)
> 
> number of mapped bases = 151 315 373 336 bp
> number of sequenced bases = 151 253 112 265 bp
> number of aligned bases = 0 bp
> ```

sample reports can be generated if the example is changed to 

> ```
> number of windows = 483
> 
> number of reads = 1,066,442,816
> number of mapped reads = 1,049,993,798 (98.46%)
> 
> number of mapped bases = 151,315,373,336 bp
> number of sequenced bases = 151,253,112,265 bp
> number of aligned bases = 0 bp
> ```

**Comment by ewels** [comment]
Hi @Smeds - is there a traceback associated?

**Comment by Smeds** [comment]
I got no traceback

Here's the terminal output I got:
>ngi_reports -n uppsala ign_sample_report --samples 235
>2015-12-09 11:24:54,883 - NGI Reports - INFO - Report type: ign_sample_report
>2015-12-09 11:24:55,563 - NGI Reports - INFO - Found 304 Piper setup XML files..
>2015-12-09 11:25:01,797 - NGI Reports - ERROR - Could not parse the ign_sample_report template for sample 235 - skipping

**Comment by aanil** [comment]
Closing this issue as ign_sample_report has been retired.
