### ISSUE TITLE
aggregate report have extra characters in column ref_above_30X

### ISSUE THREAD

**Issue by Smeds** [NationalGenomicsInfrastructure/ngi_reports#69]
Aggregate report will contain extra characters " of" when ref_abox_30X is a number without decimals.

Example

> aligned_reads  automsomal_coverage delivered   duplication_rate    id  mean_coverage   median_insert_size  percent_aligned percent_gc  ref_above_30X   run_id  ....
> 957060146  45.59   2015-09-17T08:37:11.060Z    10.61%  228 44.55X  358 99.4%   40.74%  **84% of**  H52F3CCXX  ....

**Comment by aanil** [comment]
Closing this issue as aggregate reports have been retired.
