### ISSUE TITLE
Use UPPMAX pandoc module

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/ngi_reports#73]
Johan Reimegård somehow managed to get UPPMAX to install the latest version of pandoc onto milou as a module (despite me asking for this a year ago and them saying no).

This is quite a bit more recent than the version we're using, and would mean that we don't have to bundle the pandoc binary with the repo. So could be nice to switch to that.

**Comment by aanil** [comment]
Now that we aren't going to use pandoc anymore, it should be safe to say we don't need to do this anymore.
