### ISSUE TITLE
Disabling PDF generation 

### ISSUE THREAD

**Issue by senthil10** [NationalGenomicsInfrastructure/ngi_reports#82]
Hej @b97pla , here in Stockholm we decided to drop `pdf` from our reports (so only use `html`s). I am planning to make a **PR**, so wondering if I can remove in general or just for Stockholm. Do you guys are using *PDF*s ?

**Comment by senthil10** [comment]
For time being made a **[PR](https://github.com/NationalGenomicsInfrastructure/ngi_reports/pull/83)** to disable just for *Stockholm* node.

**Comment by ewels** [comment]
@b97pla - any thoughts on PDFs generally? I'm quite keen on pure HTML for report generation. It'd make this package a whole lot simpler if we could remove pandoc + XeLaTeX dependencies... (We could remove the markdown step altogether and just use a HTML template with Jina2 directly).

**Comment by johanherman** [comment]
FYI @ewels and @senthil10: Pontus is on vacation now until 8th of August.

**Comment by ewels** [comment]
Thanks @johanherman - anyone else from Uppsala have any thoughts on the topic in the mean time?

**Comment by ewels** [comment]
Ping @NationalGenomicsInfrastructure/uppsala

**Comment by b97pla** [comment]
@ewels no, we're fine with dropping PDF. sorry for the late answer
